In [4]:
from azure.storage.blob.blockblobservice import BlockBlobService
import pandas as pd
import os.path
from io import StringIO

STORAGEACCOUNTNAME= 'cdgtemp01'    
CONTAINERNAME= 'cdge'
BLOBNAME= 'DO-2019.csv' #replace this string with the data file name and extension
SASTOKEN='?sv=2019-12-12&si=interns&sr=c&sig=dv3uO8P8oMfyvFozONMJWwIDKzMQLoQR4RI3y8spQC0%3D'

blob_service = BlockBlobService(account_name=STORAGEACCOUNTNAME, account_key=None,sas_token=SASTOKEN)
blobstring = blob_service.get_blob_to_text(CONTAINERNAME,BLOBNAME,encoding='iso-8859-1').content

#store as a dataframe
df = pd.read_csv(StringIO(blobstring))
df.head(25)

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
0,84042872,7010122.0,VO21033329,1,5.22,KG,"105,600,000",B9TL3 FAN RETAINER,02.01.2019,02.01.2019,02.01.2019,5.22,1,SBS TRANSIT LTD ( SL W/SHOP )
1,84042873,7010122.0,VO21614479,1,0,KG,0,B9TL SPROCKET WHEEL,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
2,84042874,7010121.0,VO70342913,1,0,KG,0,B10TL HYDRAULIC HOSE,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
3,84042875,7010121.0,VO1696924,1,0,KG,0,B10TL PINION,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
4,84042876,7010122.0,VO990960,1,0,KG,0,B9TL3 FLANGE LOCK NUT,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
5,84042877,7010122.0,VO22144019,2,0,KG,0,B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
6,84042878,7010295.0,VO11054692,1,0,KG,0,"B9TL,3 VALVE",03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SE W/SHOP)
7,84042878,7010295.0,VO984836,1,0,KG,0,OLY3 FLANGE SCREW,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SE W/SHOP)
8,84042879,7010122.0,VO990962,1,2.76,KG,0,"B9TL,3 FLANGE LOCK NUT",03.01.2019,03.01.2019,03.01.2019,2.76,1,SBS TRANSIT LTD ( SL W/SHOP )
9,84042880,7010122.0,VO22417892,2,0,KG,0,B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
10,84042881,7010121.0,VO3195854,1,0,KG,0,B9TL VALVE,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
11,84042882,7010120.0,VO70309430,2,0,KG,0,"B9TL,3 HOSE",03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( AM W/SHOP )
12,84042882,7010120.0,VO955918,8,0,KG,0,SPRING WASHER,03.01.2019,03.01.2019,03.01.2019,0,8,SBS TRANSIT LTD ( AM W/SHOP )
13,84042882,7010120.0,VO994781,1,0,KG,0,B9TL SIX POINT SOCKET S,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( AM W/SHOP )
14,84042883,7010121.0,VO978881,10,0,KG,0,B9TL5 PLASTIC PIPE (MOQ 10),03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( BN W/SHOP )
15,84042884,7010124.0,VO22129960,2,0,KG,0,B5LH B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( BB W/SHOP )
16,84042885,7010124.0,VO978880,10,0.85,KG,"5,760,000","B9TL,3 PIPE ( supply as 10m uncut )",03.01.2019,03.01.2019,03.01.2019,0.85,10,SBS TRANSIT LTD ( BB W/SHOP )
17,84042886,7010122.0,VO21244697,10,0,KG,0,B9TL3 RELAY,03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( SL W/SHOP )
18,84042887,7010122.0,VO21827826,1,0,KG,0,B9TL5 BUTTON,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
19,84042887,7010122.0,VO21827823,1,0,KG,0,B9TL5 BUTTON,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
20,84042887,7010122.0,VO20769509,1,2.76,KG,0,B9TL5 CONTACT,03.01.2019,03.01.2019,03.01.2019,2.76,1,SBS TRANSIT LTD ( SL W/SHOP )
21,84042888,7010122.0,VO21390375,2,0,KG,0,B9TL5 SENSOR,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
22,84042889,7010122.0,VO22194741,4,0,KG,0,"B9TL,5 SENSOR",03.01.2019,03.01.2019,03.01.2019,0,4,SBS TRANSIT LTD ( SL W/SHOP )
23,84042890,7010122.0,VO3018321,10,0,KG,0,"B9TL3 SCREW,CK-MECH,CK-SHFT",03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( SL W/SHOP )
24,84042890,7010122.0,VO22070237,1,0,KG,0,B9TL3 PROPELLER SHAFT,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345076 entries, 0 to 345075
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Delivery ID                345073 non-null  object
 1   Ship-to Key                345072 non-null  float64
 2   Material                   345072 non-null  object
 3       Dlv.qty                345072 non-null  object
 4     Total Weight             345072 non-null  object
 5   WUn                        345073 non-null  object
 6         Volume               345073 non-null  object
 7   Description                345073 non-null  object
 8   Deliv.date                 345072 non-null  object
 9   TrpPlanDt                  345071 non-null  object
 10  Pick Date                  345071 non-null  object
 11      Net weight             345072 non-null  object
 12      Dlv.qty.1              345071 non-null  object
 13  Name of the ship-to party  345071 non-null  object
dtypes: float64(1), object(13)
memory usage: 36.9+ MB

In [6]:
from azure.storage.blob.blockblobservice import BlockBlobService
import pandas as pd
import os.path
from io import StringIO

STORAGEACCOUNTNAME= 'cdgtemp01'    
CONTAINERNAME= 'cdge'
BLOBNAME= 'Ship-To-PostalCode.csv' #replace this string with the data file name and extension
SASTOKEN='?sv=2019-12-12&si=interns&sr=c&sig=dv3uO8P8oMfyvFozONMJWwIDKzMQLoQR4RI3y8spQC0%3D'

blob_service = BlockBlobService(account_name=STORAGEACCOUNTNAME, account_key=None,sas_token=SASTOKEN)
blobstring = blob_service.get_blob_to_text(CONTAINERNAME,BLOBNAME,encoding='iso-8859-1').content

#store as a dataframe
df2 = pd.read_csv(StringIO(blobstring))
df2.head(25)

   Ship-to Key                                 Name Postal Code
0            1            BLOCK -MOHAMMAD NOORJASAH      510725
1            6                 BLOCK -TEO CHEE MENG      510104
2            7                                  TOH      520388
3           11             BLOCK -AZMI BIN A RASHID      520312
4           12       BLOCK -EMERLIN TOH KENG CHING?      730010
5           16                  BLOCK -JOHAR JOHARI      640464
6           17                 BLOCK -JOHOR B-JOHOR      640404
7           18               BLOCK -ROSLAN BIN PANI      640464
8           21  BLOCK -TARGET FOOD PRODUCTS PTE LTD      118529
9           22               BLOCK -CHAN CHEK HORNG      601287
10          23               BLOCK -CHAN CHEK HORNG      601287
11          24                   BLOCK -SERENE CHOO      510703
12          26                 BLOCK -LAU HIENG SIK      128140
13          27    BLOCK -ASIA ENTERPRISES (PTE) LTD      609203
14          28    BLOCK -ASIA ENTERPRISES (PTE) LTD      609203
15          29               BLOCK -LEONG ROBIN YEE      138684
16          30               BLOCK -LEONG ROBIN YEE      138684
17          31                    BLOCK -LIM KIN HO      596939
18          32                   BLOCK -LIM POH LEE      999999
19          36        BLOCK -CHAN TUCK FATT CHARLIE      510115
20          37                  BLOCK -ONG KOK HENG         NaN
21          38                   BLOCK -SARAVANAN S      670124
22          41                       BLOCK -SAM SOO         NaN
23          42                BLOCK -HOW SOON HOONG      730866
24          43                   BLOCK -TAY GEK TIN      570017

In [8]:
df2[df2['Ship-to Key'] == '7010122']

    Ship-to Key                           Name Postal Code
396     7010122  SBS TRANSIT LTD ( SL W/SHOP )      628083

### DO-2019

In [3]:
from io import StringIO
import pandas as pd
from azure.storage.blob import BlobClient, BlobServiceClient
import numpy as np
import pandas as pd
import datetime

In [146]:
#!pip install azure-storage-blob --pre
STORAGEACCOUNTNAME= 'cdgtemp01'    
CONTAINERNAME= 'cdge'
BLOBNAME= 'DO-2019.csv' #replace this string with the data file name and extension
sastoken = '?sv=2019-12-12&si=interns&sr=c&sig=dv3uO8P8oMfyvFozONMJWwIDKzMQLoQR4RI3y8spQC0%3D'
url='https://cdgtemp01.blob.core.windows.net'

blob_service_client = BlobServiceClient(account_url=url,credential=sastoken)
blob_client = blob_service_client.get_blob_client(container=CONTAINERNAME, blob=BLOBNAME)
blob = blob_client.download_blob().content_as_text(encoding='iso-8859-1')

#store as a dataframe
df = pd.read_csv(StringIO(blob))
df.head(25)

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
0,84042872,7010122.0,VO21033329,1,5.22,KG,"105,600,000",B9TL3 FAN RETAINER,02.01.2019,02.01.2019,02.01.2019,5.22,1,SBS TRANSIT LTD ( SL W/SHOP )
1,84042873,7010122.0,VO21614479,1,0,KG,0,B9TL SPROCKET WHEEL,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
2,84042874,7010121.0,VO70342913,1,0,KG,0,B10TL HYDRAULIC HOSE,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
3,84042875,7010121.0,VO1696924,1,0,KG,0,B10TL PINION,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
4,84042876,7010122.0,VO990960,1,0,KG,0,B9TL3 FLANGE LOCK NUT,02.01.2019,02.01.2019,02.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
5,84042877,7010122.0,VO22144019,2,0,KG,0,B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
6,84042878,7010295.0,VO11054692,1,0,KG,0,"B9TL,3 VALVE",03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SE W/SHOP)
7,84042878,7010295.0,VO984836,1,0,KG,0,OLY3 FLANGE SCREW,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SE W/SHOP)
8,84042879,7010122.0,VO990962,1,2.76,KG,0,"B9TL,3 FLANGE LOCK NUT",03.01.2019,03.01.2019,03.01.2019,2.76,1,SBS TRANSIT LTD ( SL W/SHOP )
9,84042880,7010122.0,VO22417892,2,0,KG,0,B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
10,84042881,7010121.0,VO3195854,1,0,KG,0,B9TL VALVE,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( BN W/SHOP )
11,84042882,7010120.0,VO70309430,2,0,KG,0,"B9TL,3 HOSE",03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( AM W/SHOP )
12,84042882,7010120.0,VO955918,8,0,KG,0,SPRING WASHER,03.01.2019,03.01.2019,03.01.2019,0,8,SBS TRANSIT LTD ( AM W/SHOP )
13,84042882,7010120.0,VO994781,1,0,KG,0,B9TL SIX POINT SOCKET S,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( AM W/SHOP )
14,84042883,7010121.0,VO978881,10,0,KG,0,B9TL5 PLASTIC PIPE (MOQ 10),03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( BN W/SHOP )
15,84042884,7010124.0,VO22129960,2,0,KG,0,B5LH B9TL5 COOLING HOSE,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( BB W/SHOP )
16,84042885,7010124.0,VO978880,10,0.85,KG,"5,760,000","B9TL,3 PIPE ( supply as 10m uncut )",03.01.2019,03.01.2019,03.01.2019,0.85,10,SBS TRANSIT LTD ( BB W/SHOP )
17,84042886,7010122.0,VO21244697,10,0,KG,0,B9TL3 RELAY,03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( SL W/SHOP )
18,84042887,7010122.0,VO21827826,1,0,KG,0,B9TL5 BUTTON,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
19,84042887,7010122.0,VO21827823,1,0,KG,0,B9TL5 BUTTON,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )
20,84042887,7010122.0,VO20769509,1,2.76,KG,0,B9TL5 CONTACT,03.01.2019,03.01.2019,03.01.2019,2.76,1,SBS TRANSIT LTD ( SL W/SHOP )
21,84042888,7010122.0,VO21390375,2,0,KG,0,B9TL5 SENSOR,03.01.2019,03.01.2019,03.01.2019,0,2,SBS TRANSIT LTD ( SL W/SHOP )
22,84042889,7010122.0,VO22194741,4,0,KG,0,"B9TL,5 SENSOR",03.01.2019,03.01.2019,03.01.2019,0,4,SBS TRANSIT LTD ( SL W/SHOP )
23,84042890,7010122.0,VO3018321,10,0,KG,0,"B9TL3 SCREW,CK-MECH,CK-SHFT",03.01.2019,03.01.2019,03.01.2019,0,10,SBS TRANSIT LTD ( SL W/SHOP )
24,84042890,7010122.0,VO22070237,1,0,KG,0,B9TL3 PROPELLER SHAFT,03.01.2019,03.01.2019,03.01.2019,0,1,SBS TRANSIT LTD ( SL W/SHOP )

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345076 entries, 0 to 345075
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Delivery ID                345073 non-null  object
 1   Ship-to Key                345072 non-null  float64
 2   Material                   345072 non-null  object
 3       Dlv.qty                345072 non-null  object
 4     Total Weight             345072 non-null  object
 5   WUn                        345073 non-null  object
 6         Volume               345073 non-null  object
 7   Description                345073 non-null  object
 8   Deliv.date                 345072 non-null  object
 9   TrpPlanDt                  345071 non-null  object
 10  Pick Date                  345071 non-null  object
 11      Net weight             345072 non-null  object
 12      Dlv.qty.1              345071 non-null  object
 13  Name of the ship-to party  345071 non-null  object
dtypes: float64(1), object(13)
memory usage: 36.9+ MB

In [149]:
df.columns = ['Delivery ID', 'Ship-to Key', 'Material', 'Dlv.qty', 'Total Weight', 'WUn', 'Volume', 'Description', 
              'Deliv.date', 'TrpPlanDt', 'Pick Date', 'Net weight', 'Dlv.qty.1', 'Name of the ship-to party']

In [150]:
df[df['Ship-to Key'].isnull()]

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
193659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193662,Singapore,NaN,NaN,NaN,NaN,CESO,L6,DECCPR01,C,NaN,NaN,1F18A,NaN,NaN

In [151]:
df = df.dropna(subset=['Ship-to Key'])

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 345072 entries, 0 to 345075
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Delivery ID                345072 non-null  object
 1   Ship-to Key                345072 non-null  float64
 2   Material                   345072 non-null  object
 3   Dlv.qty                    345072 non-null  object
 4   Total Weight               345072 non-null  object
 5   WUn                        345072 non-null  object
 6   Volume                     345072 non-null  object
 7   Description                345072 non-null  object
 8   Deliv.date                 345071 non-null  object
 9   TrpPlanDt                  345071 non-null  object
 10  Pick Date                  345071 non-null  object
 11  Net weight                 345071 non-null  object
 12  Dlv.qty.1                  345071 non-null  object
 13  Name of the ship-to party  345071 non-null  object
dtypes: float64(1), object(13)
memory usage: 39.5+ MB

In [153]:
df = df.reset_index()

In [198]:
# dulicated data -> at that one day has many trips to that one location or error?
# some  data total weight = 0 -> error?
df[df.duplicated(keep=False)]

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
8812,760142263,80411122,VO20535875,12.0,17.424,KG,132600000.0,B5LH B9TL5 BELLOWS,2019-02-15,2019-02-15,2019-02-15,17.424,12,SMRT WOODLANDS
8813,760142263,80411122,VO20535875,12.0,17.424,KG,132600000.0,B5LH B9TL5 BELLOWS,2019-02-15,2019-02-15,2019-02-15,17.424,12,SMRT WOODLANDS
13202,760143964,7010120,VO21477174,5.0,0.000,KG,375000000.0,B9TL5 REACTION ROD,2019-03-19,2019-03-19,2019-03-19,0.000,5,SBS TRANSIT LTD ( AM W/SHOP )
13203,760143964,7010120,VO21477174,5.0,0.000,KG,375000000.0,B9TL5 REACTION ROD,2019-03-19,2019-03-19,2019-03-19,0.000,5,SBS TRANSIT LTD ( AM W/SHOP )
14111,760144283,7010122,VO21054681,1.0,0.000,KG,0.0,B9TL3 COVER,2019-04-15,2019-04-15,2019-04-15,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345055,890356791,7010122,VO22807178,1.0,0.000,KG,0.0,B9TL STARTER MOTOR,2019-11-18,2019-11-18,2019-11-18,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )
345056,890356791,7010122,VO22807178,1.0,0.000,KG,0.0,B9TL STARTER MOTOR,2019-11-18,2019-11-18,2019-11-18,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )
345057,890356791,7010122,VO22807178,1.0,0.000,KG,0.0,B9TL STARTER MOTOR,2019-11-18,2019-11-18,2019-11-18,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )
345058,890356791,7010122,VO22807178,1.0,0.000,KG,0.0,B9TL STARTER MOTOR,2019-11-18,2019-11-18,2019-11-18,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )
345059,890356791,7010122,VO22807178,1.0,0.000,KG,0.0,B9TL STARTER MOTOR,2019-11-18,2019-11-18,2019-11-18,0.000,1,SBS TRANSIT LTD ( SL W/SHOP )

In [155]:
df['Ship-to Key'].apply(float.is_integer).all()

True

In [156]:
df['Ship-to Key'] = df['Ship-to Key'].astype('int64')

In [157]:
def convert_to_float(value):
    try:
        value = float(value)
    except ValueError:
        value = value.replace(',','')
        value = float(value)
    return value

In [158]:
df['Dlv.qty'] = df['Dlv.qty'].apply(convert_to_float)

In [159]:
df['Total Weight'] = df['Total Weight'].apply(convert_to_float)

In [160]:
df['Volume'] = df['Volume'].apply(convert_to_float)

In [161]:
df['Net weight'] = df['Net weight'].apply(convert_to_float)

In [162]:
df = df.drop('index', axis=1)

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345072 entries, 0 to 345071
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Delivery ID                345072 non-null  object
 1   Ship-to Key                345072 non-null  int64
 2   Material                   345072 non-null  object
 3   Dlv.qty                    345072 non-null  float64
 4   Total Weight               345072 non-null  float64
 5   WUn                        345072 non-null  object
 6   Volume                     345072 non-null  float64
 7   Description                345072 non-null  object
 8   Deliv.date                 345071 non-null  object
 9   TrpPlanDt                  345071 non-null  object
 10  Pick Date                  345071 non-null  object
 11  Net weight                 345071 non-null  float64
 12  Dlv.qty.1                  345071 non-null  object
 13  Name of the ship-to party  345071 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 36.9+ MB

In [164]:
len(df[df['WUn'] == 'KG'])

345072

In [165]:
df[df['Deliv.date'].isnull()]

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
193658,890251024,8047087,28-03-0000-0016-A,2.0,0.0,KG,0.0,"""BICYCLE TYRE TUBE 26""""(FRONT)(REAR)\t05.07.20...",NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
df = df.dropna(subset=['Deliv.date'])

In [167]:
df['Deliv.date'] = df['Deliv.date'].apply(lambda x: datetime.datetime.strptime(str(x), '%d.%m.%Y').date())
df['TrpPlanDt'] = df['TrpPlanDt'].apply(lambda x: datetime.datetime.strptime(str(x), '%d.%m.%Y').date())
df['Pick Date'] = df['Pick Date'].apply(lambda x: datetime.datetime.strptime(str(x), '%d.%m.%Y').date())

In [168]:
df['Deliv.date'] = df['Deliv.date'].astype('datetime64[ns]')
df['TrpPlanDt'] = df['TrpPlanDt'].astype('datetime64[ns]')
df['Pick Date'] = df['Pick Date'].astype('datetime64[ns]')

In [169]:
df['Delivery ID'] = df['Delivery ID'].astype(int)

In [170]:
df.head()

,Delivery ID,Ship-to Key,Material,Dlv.qty,Total Weight,WUn,Volume,Description,Deliv.date,TrpPlanDt,Pick Date,Net weight,Dlv.qty.1,Name of the ship-to party
0,84042872,7010122,VO21033329,1.0,5.22,KG,105600000.0,B9TL3 FAN RETAINER,2019-01-02,2019-01-02,2019-01-02,5.22,1,SBS TRANSIT LTD ( SL W/SHOP )
1,84042873,7010122,VO21614479,1.0,0.00,KG,0.0,B9TL SPROCKET WHEEL,2019-01-02,2019-01-02,2019-01-02,0.00,1,SBS TRANSIT LTD ( SL W/SHOP )
2,84042874,7010121,VO70342913,1.0,0.00,KG,0.0,B10TL HYDRAULIC HOSE,2019-01-02,2019-01-02,2019-01-02,0.00,1,SBS TRANSIT LTD ( BN W/SHOP )
3,84042875,7010121,VO1696924,1.0,0.00,KG,0.0,B10TL PINION,2019-01-02,2019-01-02,2019-01-02,0.00,1,SBS TRANSIT LTD ( BN W/SHOP )
4,84042876,7010122,VO990960,1.0,0.00,KG,0.0,B9TL3 FLANGE LOCK NUT,2019-01-02,2019-01-02,2019-01-02,0.00,1,SBS TRANSIT LTD ( SL W/SHOP )

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 345071 entries, 0 to 345071
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Delivery ID                345071 non-null  int32
 1   Ship-to Key                345071 non-null  int64
 2   Material                   345071 non-null  object
 3   Dlv.qty                    345071 non-null  float64
 4   Total Weight               345071 non-null  float64
 5   WUn                        345071 non-null  object
 6   Volume                     345071 non-null  float64
 7   Description                345071 non-null  object
 8   Deliv.date                 345071 non-null  datetime64[ns]
 9   TrpPlanDt                  345071 non-null  datetime64[ns]
 10  Pick Date                  345071 non-null  datetime64[ns]
 11  Net weight                 345071 non-null  float64
 12  Dlv.qty.1                  345071 non-null  object
 13  Name of the ship-to party  345071 non-null  object
dtypes: datetime64[ns](3), float64(4), int32(1), int64(1), object(5)
memory usage: 38.2+ MB

### Ship-To-PostalCode

In [4]:
STORAGEACCOUNTNAME= 'cdgtemp01'    
CONTAINERNAME= 'cdge'
BLOBNAME= 'Ship-To-PostalCode.csv' #replace this string with the data file name and extension
sastoken = '?sv=2019-12-12&si=interns&sr=c&sig=dv3uO8P8oMfyvFozONMJWwIDKzMQLoQR4RI3y8spQC0%3D'
url='https://cdgtemp01.blob.core.windows.net'

blob_service_client = BlobServiceClient(account_url=url,credential=sastoken)
blob_client = blob_service_client.get_blob_client(container=CONTAINERNAME, blob=BLOBNAME)
blob = blob_client.download_blob().content_as_text(encoding='iso-8859-1')

#store as a dataframe
df2 = pd.read_csv(StringIO(blob))
df2.head(25)

   Ship-to Key                                 Name Postal Code
0            1            BLOCK -MOHAMMAD NOORJASAH      510725
1            6                 BLOCK -TEO CHEE MENG      510104
2            7                                  TOH      520388
3           11             BLOCK -AZMI BIN A RASHID      520312
4           12       BLOCK -EMERLIN TOH KENG CHING?      730010
5           16                  BLOCK -JOHAR JOHARI      640464
6           17                 BLOCK -JOHOR B-JOHOR      640404
7           18               BLOCK -ROSLAN BIN PANI      640464
8           21  BLOCK -TARGET FOOD PRODUCTS PTE LTD      118529
9           22               BLOCK -CHAN CHEK HORNG      601287
10          23               BLOCK -CHAN CHEK HORNG      601287
11          24                   BLOCK -SERENE CHOO      510703
12          26                 BLOCK -LAU HIENG SIK      128140
13          27    BLOCK -ASIA ENTERPRISES (PTE) LTD      609203
14          28    BLOCK -ASIA ENTERPRISES (PTE) LTD      609203
15          29               BLOCK -LEONG ROBIN YEE      138684
16          30               BLOCK -LEONG ROBIN YEE      138684
17          31                    BLOCK -LIM KIN HO      596939
18          32                   BLOCK -LIM POH LEE      999999
19          36        BLOCK -CHAN TUCK FATT CHARLIE      510115
20          37                  BLOCK -ONG KOK HENG         NaN
21          38                   BLOCK -SARAVANAN S      670124
22          41                       BLOCK -SAM SOO         NaN
23          42                BLOCK -HOW SOON HOONG      730866
24          43                   BLOCK -TAY GEK TIN      570017

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215769 entries, 0 to 215768
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Ship-to Key  215769 non-null  object
 1   Name         212280 non-null  object
 2   Postal Code  193607 non-null  object
dtypes: object(3)
memory usage: 4.9+ MB

In [6]:
df2[df2['Name'].isnull()]

       Ship-to Key Name Postal Code
929        8030092  NaN         NaN
945        8030108  NaN         NaN
977        8030140  NaN         NaN
997        8030160  NaN         NaN
998        8030161  NaN         NaN
...            ...  ...         ...
139665   805219833  NaN         NaN
139728   805219896  NaN         NaN
139758   805219926  NaN         NaN
215392   807000327  NaN         NaN
215710   807000686  NaN         NaN

[3489 rows x 3 columns]

In [7]:
nan_keys = df2[df2['Name'].isnull()]['Ship-to Key'].values.astype(int)

In [8]:
nan_keys

array([  8030092,   8030108,   8030140, ..., 805219926, 807000327,
       807000686])

In [9]:
def check_ship_key(value):
    if value in nan_keys:
        print(value)

In [ ]:
df['Ship-to Key'].apply(check_ship_key)

In [11]:
df2 = df2.dropna(subset=['Name'])

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 212280 entries, 0 to 215768
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Ship-to Key  212280 non-null  object
 1   Name         212280 non-null  object
 2   Postal Code  193576 non-null  object
dtypes: object(3)
memory usage: 6.5+ MB

In [13]:
df2[df2['Postal Code'].isnull()]

       Ship-to Key                 Name Postal Code
20              37  BLOCK -ONG KOK HENG         NaN
22              41       BLOCK -SAM SOO         NaN
25              44   BLOCK -OH LAWRENCE         NaN
28              51   BLOCK -TANG MA YUK         NaN
30              56       BLOCK -IBRAHIM         NaN
...            ...                  ...         ...
215728   807000761         TAN KING KIM         NaN
215739   807000800        WONG SENG LEE         NaN
215741   807000810             S.K.VELU         NaN
215744   807000825                 CTPL         NaN
215762       C0010       One Time - M&P         NaN

[18704 rows x 3 columns]

### Inventory-Master-December-2020

In [192]:
STORAGEACCOUNTNAME= 'cdgtemp01'    
CONTAINERNAME= 'cdge'
BLOBNAME= 'Inventory-Master-December-2020.csv' #replace this string with the data file name and extension
sastoken = '?sv=2019-12-12&si=interns&sr=c&sig=dv3uO8P8oMfyvFozONMJWwIDKzMQLoQR4RI3y8spQC0%3D'
url='https://cdgtemp01.blob.core.windows.net'

blob_service_client = BlobServiceClient(account_url=url,credential=sastoken)
blob_client = blob_service_client.get_blob_client(container=CONTAINERNAME, blob=BLOBNAME)
blob = blob_client.download_blob().content_as_text(encoding='iso-8859-1')

#store as a dataframe
df3 = pd.read_csv(StringIO(blob))
df3.head(25)

,ï»¿Sno,CDGE Part No,Part Description,Model,MRP Ctrl,MRP Grp,ABC Ind,Plant,UOM,QOH
0,1,000 357 0191,212VC BOOT REPAIR KIT OUTER BOOT,T14-03,T10,2,D,CLY,PC,6.0
1,2,000 540 0966,212VC LAMP HOLDERÂ,E220,T10,3,D,CLY,PC,2.0
2,3,000 630 4510,639VA RIGHT CORNER PILLAR BOTTOM,VIANO,T11,2,D,CLY,PC,2.0
3,4,000 637 1019,639VA PILLAR CORNER RIGHT,VIANO,T11,2,D,CLY,PC,2.0
4,5,000 692 3104,639VA SIDE PANEL TRIM RHS,VIANO,T11,1,D,CLY,PC,2.0
5,6,000 694 0825,639VA PANEL HINGE RIGHT BOTTOM,VIANO,T11,3,D,CLY,PC,2.0
6,7,000 747 4771,639VA TAIL GATE FOIL,VIANO,T11,3,D,CLY,PC,2.0
7,8,000 766 0262,639VA STARTUP WEDGE BOTTOM RIGHT,VIANO,T11,2,D,CLY,PC,2.0
8,9,000 988 0152,212VC AT SOLENOID,T15-01,T10,NaN,NaN,CLY,EAC,7.0
9,10,000 991 5252,639VA CYLINDRICAL PIN,VIANO,T11,3,C,CLY,PC,10.0
10,11,000 991 6098,212VC CLIP LH/RH,E220,T10,4,D,CLY,PC,13.0
11,12,000 991 7298,212VC CLIP LOWER 20MM,E220,T10,4,C,CLY,PC,19.0
12,13,000 991 7398,212VC CLIP LOWER 10MM,E220,T10,4,C,CLY,PC,12.0
13,14,000 991 7498,212VC TRIM CLIP UPPER,E220,T10,4,C,CLY,PC,39.0
14,15,000 998 1495,212VA ROTARY CATCHÂ,E220,T10,4,D,CLY,PC,2.0
15,16,000 998 5323,212VA BATT PROTECTIVE CAP,E220,T10,4,D,CLY,PC,1.0
16,17,1080268,B9 Front Bumper LH,BDD,B09,NaN,NaN,CBMS,EAC,1.0
17,18,1080269,B9 R/H Corner Bumper,BDD,B09,NaN,NaN,CBMS,EAC,3.0
18,19,1080270,B9 Front Bumper Centre,BDD,B09,NaN,NaN,CBMS,EAC,2.0
19,20,1080362,B9 Upper Rear Exterior,BDD,B09,NaN,NaN,CBMS,EAC,1.0
20,21,1080452,B9 Rear Bumper LH,BDD,B09,NaN,NaN,CBMS,EAC,2.0
21,22,1080453,B9 Rear Bumper RH,BDD,B09,NaN,NaN,CBMS,EAC,3.0
22,23,1080454,B9 Rear Bumper Centre,BDD,B09,NaN,NaN,CBMS,EAC,1.0
23,24,1080514,B9 Staircase Side Wall Glass,BDD,B09,NaN,NaN,CSG,EAC,4.0
24,25,1080582,B9 Side Glass Upper Front LH,BDD,B09,NaN,NaN,CSG,EAC,11.0

In [196]:
df3 = df3.drop('ï»¿Sno', axis=1)

In [197]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10121 entries, 0 to 10120
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CDGE Part No      10121 non-null  object
 1   Part Description  10121 non-null  object
 2   Model             10121 non-null  object
 3   MRP Ctrl          10072 non-null  object
 4   MRP Grp           6167 non-null   object
 5   ABC Ind           5892 non-null   object
 6   Plant             10121 non-null  object
 7   UOM               10121 non-null  object
 8   QOH               10121 non-null  float64
dtypes: float64(1), object(8)
memory usage: 711.8+ KB